version: "3.12"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  app:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      UPLOAD_DIR: ${UPLOAD_DIR}
    volumes:
      - ./uploads:${UPLOAD_DIR}

  nginx:
    build: deploy/nginx
    restart: always
    volumes:
      - nginx-logs:/var/log/nginx
      - ./deploy/js:/usr/share/nginx/html
    depends_on:
      - app
    ports:
      - ${LISTEN_PORT}:80
volumes:
  data:
  nginx-logs:
